<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8IGzJn0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8IGzJn0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8IGzJn0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8IGzJn0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8IGzJn0\App_KernelDevDebugContainer([
    'container.build_hash' => '8IGzJn0',
    'container.build_id' => '12a179df',
    'container.build_time' => 1701950716,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8IGzJn0');
