<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFDyFrvp\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFDyFrvp/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFDyFrvp.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFDyFrvp\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFDyFrvp\App_KernelDevDebugContainer([
    'container.build_hash' => 'FDyFrvp',
    'container.build_id' => '05696698',
    'container.build_time' => 1701641600,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFDyFrvp');
