<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4VX4fx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4VX4fx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA4VX4fx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA4VX4fx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA4VX4fx\App_KernelDevDebugContainer([
    'container.build_hash' => 'A4VX4fx',
    'container.build_id' => '294eb8bb',
    'container.build_time' => 1702160288,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4VX4fx');
